/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramasPlanMaestroRouteImport } from './routes/programas.plan-maestro'

const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasPlanMaestroRoute = ProgramasPlanMaestroRouteImport.update({
  id: '/plan-maestro',
  path: '/plan-maestro',
  getParentRoute: () => ProgramasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programas': typeof ProgramasRouteWithChildren
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programas' | '/programas/plan-maestro'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programas' | '/programas/plan-maestro'
  id: '__root__' | '/' | '/programas' | '/programas/plan-maestro'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramasRoute: typeof ProgramasRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/plan-maestro': {
      id: '/programas/plan-maestro'
      path: '/plan-maestro'
      fullPath: '/programas/plan-maestro'
      preLoaderRoute: typeof ProgramasPlanMaestroRouteImport
      parentRoute: typeof ProgramasRoute
    }
  }
}

interface ProgramasRouteChildren {
  ProgramasPlanMaestroRoute: typeof ProgramasPlanMaestroRoute
}

const ProgramasRouteChildren: ProgramasRouteChildren = {
  ProgramasPlanMaestroRoute: ProgramasPlanMaestroRoute,
}

const ProgramasRouteWithChildren = ProgramasRoute._addFileChildren(
  ProgramasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramasRoute: ProgramasRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
