/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgramasIndexRouteImport } from './routes/programas.index'
import { Route as ProgramasPlanMaestroRouteImport } from './routes/programas.plan-maestro'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasIndexRoute = ProgramasIndexRouteImport.update({
  id: '/programas/',
  path: '/programas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasPlanMaestroRoute = ProgramasPlanMaestroRouteImport.update({
  id: '/plan-maestro',
  path: '/plan-maestro',
  getParentRoute: () => ProgramasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
  '/programas': typeof ProgramasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/programas/plan-maestro': typeof ProgramasPlanMaestroRoute
  '/programas/': typeof ProgramasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/programas/plan-maestro' | '/programas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/programas/plan-maestro' | '/programas'
  id: '__root__' | '/' | '/programas/plan-maestro' | '/programas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgramasIndexRoute: typeof ProgramasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/': {
      id: '/programas/'
      path: '/programas'
      fullPath: '/programas/'
      preLoaderRoute: typeof ProgramasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas/plan-maestro': {
      id: '/programas/plan-maestro'
      path: '/plan-maestro'
      fullPath: '/programas/plan-maestro'
      preLoaderRoute: typeof ProgramasPlanMaestroRouteImport
      parentRoute: typeof ProgramasRoute
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgramasIndexRoute: ProgramasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
